const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
class Vector{constructor(x=0,y=0,z=0){Object.assign(this,{x,y,z})}set(x,y,z){Object.assign(this,{x,y,z});return this}clone(){return new Vector(this.x,this.y,this.z)}}
class Object3D{constructor(){this.children=[];this.position=new Vector();this.rotation={x:0,y:0,z:0};this.quaternion={clone:()=>({})};this.userData={};this.visible=true}add(m){m.parent=this;this.children.push(m)}traverse(fn){fn(this);this.children.forEach(m=>m.traverse(fn))}}
class Geometry{constructor(width,height,depth){this.parameters={width,height,depth}}}
class Mesh extends Object3D{constructor(geometry,material){super();Object.assign(this,{geometry,material,isMesh:true})}}
const THREE={Group:Object3D,Mesh,BoxGeometry:Geometry,PlaneGeometry:Geometry,CylinderGeometry:Geometry,ConeGeometry:Geometry,MeshStandardMaterial:class{constructor(p){Object.assign(this,p)}},PointLight:class extends Object3D{constructor(color,intensity,distance){super();Object.assign(this,{color,intensity,distance,isPointLight:true})}}};
THREE.AmbientLight=class extends Object3D{constructor(color,intensity){super();Object.assign(this,{color,intensity,isAmbientLight:true})}};
const gameRailwayIds=JSON.parse(fs.readFileSync('game.js','utf8').match(/createNightTrain\(\{[\s\S]{0,300}?books:(\[[\d,]+\])\.map\(id=>books\.find/)[1]);
function fixture(){const scene=new Object3D(),player={pos:new Vector(153,0,-20),radius:.42},colliders=[],interactables=[],performanceZones={},notices=[];let returns=0;const window={ATHENAEUM_EXTRA_NOTES:{},ATHENAEUM_COVER_DESIGNS:{}};
  vm.runInNewContext(fs.readFileSync('data/open-access-catalog.js','utf8'),{window});vm.runInNewContext(fs.readFileSync('data/book-completions.js','utf8'),{window});vm.runInNewContext(fs.readFileSync('data/night-railway-books.js','utf8'),{window});vm.runInNewContext(fs.readFileSync('night-train.js','utf8'),{window,Math});
  const sources=window.ATHENAEUM_OPEN_ACCESS_SOURCES,depotAcquisitions=window.ATHENAEUM_OPEN_ACCESS_BOOKS.filter(book=>book.room!=='sorting').map(book=>({...book,source:sources[book.source].name}));
  const fogBook={id:900007,title:'Lost in the Fog',author:'J. D. Beresford'};
  const railway=window.createNightTrain({THREE,scene,MAT:{wood:{},wood2:{},darkWood:{},stone:{},brass:{}},player,colliders,interactables,performanceZones,books:gameRailwayIds.map(id=>window.ATHENAEUM_RAILWAY_BOOKS.concat(depotAcquisitions).find(b=>b.id===id)||{id}),fogBook,canvasTexture:()=>({}),wrapText:()=>{},coverTexture:()=>({}),rememberLights:()=>{},notice:t=>notices.push(t),move:(x,z)=>player.pos.set(x,0,z),home:()=>{returns++;player.pos.set(0,0,24)},collider:(x,z,w,d,name,minY,maxY)=>colliders.push({minX:x-w/2,maxX:x+w/2,minZ:z-d/2,maxZ:z+d/2,name,minY,maxY})});
  return{railway,player,scene,interactables,performanceZones,window,notices,get returns(){return returns}};
}
// Since #31 journeys are conductor-led: speak to him to depart, wait out the 32-second run, then speak again to open the door.
function conductorIn(f){return f.interactables.find(object=>object.userData.key==='conductor')}
function rideOneStop(f,t=1){const r=f.railway,c=conductorIn(f);r.interact(conductorIn(f));assert(r.travelling,'conductor should start the journey');r.update(t,33,true,true,()=>{});assert(!r.travelling,'train should arrive after its run');r.interact(c)}
test('night railway is additive, lazy, isolated and has collision-safe platform, aisle and depot arrivals',()=>{const f=fixture(),r=f.railway;assert(!r.built);assert.equal(f.interactables.length,1);r.interact(r.entrance);assert(r.built);assert(r.allowed(213,-20));assert(!r.allowed(209.9,-20));r.interact(r.controls.board);assert(r.allowed(f.player.pos.x,f.player.pos.z));for(let z=-28;z<-11;z+=.05)assert(r.allowed(220.5,z),`aisle ${z}`);assert(!r.allowed(218.7,-22));assert(!r.allowed(222.25,-22));assert(!r.zoneAt(240,-20));assert(!r.allowed(240,-20));
  rideOneStop(f,1);rideOneStop(f,2);assert(!r.fogArrived);rideOneStop(f,3);assert(r.fogArrived);r.interact(r.controls.alight);assert(r.allowed(283,-20));assert.deepEqual(Object.entries(r.groups).filter(([,g])=>g.visible).map(([key])=>key),['fog-platform']);r.interact(r.controls['fog-waiting']);const lost=f.interactables.find(object=>object.userData.fogDiscovery);f.scene.add(lost);r.update(1.5,.1,true,true,()=>{});assert(r.fogFound);r.interact(r.controls['fog-return']);
  r.interact(r.entrance);r.interact(r.controls.board);for(let i=0;i<4;i++)rideOneStop(f,4+i);assert(r.arrived);r.interact(r.controls.alight);assert(r.allowed(260,-9));for(let z=-23;z<-7;z+=.1)assert(r.allowed(265,z),`depot ${z}`);for(let x=249;x<271;x+=.1)assert(r.allowed(x,-20));assert(!r.allowed(252,-26));assert(r.allowed(268,-12));
  const visible=Object.entries(r.groups).filter(([,g])=>g.visible).map(([key])=>key);assert.deepEqual(visible,['depot']);r.interact(r.controls.reboard);assert(r.allowed(220.5,-13));
});
test('journey pauses with settings, permits reading, stops at every station and waits for the conductor before opening',()=>{const f=fixture(),r=f.railway;r.interact(r.entrance);r.interact(r.controls.board);r.interact(conductorIn(f));assert(r.travelling);r.update(1,70,false,false,()=>{});assert(r.travelling,'paused train must not arrive');r.interact(r.controls.alight);assert.equal(f.player.pos.x,220.5,'cannot alight while moving');r.update(2,31,false,true,()=>{});assert(r.travelling);r.update(3,1.1,false,true,()=>{});assert(!r.travelling);const arrivals=f.notices.filter(t=>t.includes('slows beneath')).length;assert.equal(arrivals,1);r.update(4,100,false,true,()=>{});assert.equal(f.notices.filter(t=>t.includes('slows beneath')).length,arrivals,'arrival is announced once');r.interact(r.controls.alight);assert.equal(f.player.pos.x,220.5,'door stays shut until the conductor opens it');r.interact(conductorIn(f));assert.equal(r.controls.alight.userData.action,'ALIGHT AT THE SIGNAL HOUSE');r.interact(r.controls.alight);assert.equal(f.player.pos.x,332);r.interact(r.controls['signal-reboard']);for(let i=0;i<3;i++)rideOneStop(f,5+i);assert(r.arrived);assert(!r.travelling);assert.equal(r.controls.alight.userData.action,'ALIGHT AT THE COLLECTIONS DEPOT');
});
test('the way home is always available, emergency reset cancels travel and no objects accumulate on repeat visits',()=>{const f=fixture(),r=f.railway;r.interact(r.entrance);r.interact(r.controls['platform-home']);assert.equal(f.returns,1);assert.equal(f.player.pos.x,0);r.interact(r.entrance);r.interact(r.controls.board);r.interact(conductorIn(f));assert(r.travelling);r.interact(r.controls['car-home']);assert(r.travelling,'the window ticket explains the route rather than teleporting');assert.match(f.notices.at(-1),/conductor/);r.cancel();assert(!r.travelling);const count=f.interactables.length;r.interact(r.entrance);assert.equal(f.interactables.length,count);r.interact(r.controls.board);for(let i=0;i<5;i++)rideOneStop(f,1+i);r.interact(r.controls.alight);assert.equal(f.player.pos.x,213,'a full loop returns to the Library Platform');r.interact(r.controls['platform-home']);assert.equal(f.returns,2);r.interact(r.controls['depot-home']);assert.equal(f.returns,2);assert.match(f.notices.at(-1),/conductor/);assert.equal(f.interactables.length,count);assert(!r.interact({userData:{type:'book'}}));});
test('all three original railway books keep covers, notes and complete online and offline editions',()=>{const f=fixture();for(const book of f.window.ATHENAEUM_RAILWAY_BOOKS){assert(f.window.ATHENAEUM_EXTRA_NOTES[book.id]);assert(f.window.ATHENAEUM_COVER_DESIGNS[book.id]);assert(book.depotNote);const text=fs.readFileSync(`texts/pg${book.id}.txt`,'utf8');assert(text.length>100000);assert.match(text,/END OF (?:THE|THIS) PROJECT GUTENBERG EBOOK/);const local={window:{}};vm.runInNewContext(fs.readFileSync(`texts/local/pg${book.id}.js`,'utf8'),local);assert.equal(local.window.ATHENAEUM_LOCAL_TEXTS[book.id].replace(/\r\n/g,'\n'),text.replace(/\r\n/g,'\n'))}});
test('six obscure depot acquisitions span three non-Gutenberg sources with covers, notes and local editions',()=>{const f=fixture(),books=f.window.ATHENAEUM_OPEN_ACCESS_BOOKS.filter(book=>book.room!=='sorting');assert.equal(books.length,6);assert.deepEqual([...new Set(books.map(book=>book.source))].sort(),['internet-archive','standard-ebooks','wikisource']);for(const book of books){assert(f.window.ATHENAEUM_EXTRA_NOTES[book.id]?.length>100);assert(f.window.ATHENAEUM_COVER_DESIGNS[book.id]);assert(book.depotNote?.length>100);assert.notEqual(book.source,'project-gutenberg');const text=fs.readFileSync(book.textPath,'utf8');assert(text.length>40000);const local={window:{}};vm.runInNewContext(fs.readFileSync(`texts/local/pg${book.id}.js`,'utf8'),local);assert.equal(local.window.ATHENAEUM_LOCAL_TEXTS[book.id].replace(/\r\n/g,'\n'),text.replace(/\r\n/g,'\n'))}f.railway.build();const copies=f.interactables.filter(m=>m.userData.railwayCopy),depotCopies=copies.filter(m=>m.parent===f.railway.groups.depot);assert.equal(depotCopies.length,gameRailwayIds.length);assert.equal(copies.length,6+gameRailwayIds.length+1+4);assert.equal(copies.filter(m=>m.parent===f.railway.groups['signal-room']).length,2);assert.equal(copies.filter(m=>m.parent===f.railway.groups['tide-room']).length,2);copies.forEach(m=>{assert.equal(m.userData.type,'book');assert.equal(m.userData.home.parent,m.parent);assert(m.userData.realCover)});const cards=Object.values(f.railway.controls).filter(m=>m.userData.key.startsWith('card-'));assert.equal(cards.length,6);cards.forEach(card=>assert(card.userData.note.length>100));});
test('railway portals, carriage and seating retain their Victorian detail and local CC0 hardware',()=>{const f=fixture(),r=f.railway,source=fs.readFileSync('night-train.js','utf8');assert.equal(r.entrance.userData.action,'ENTER PLATFORM');r.build();assert.equal(r.controls.board.position.x,217.79);assert.equal(r.controls.board.userData.action,'BOARD');assert.match(source,/NIGHT PLATFORM/);assert.match(source,/function carriageSeat/);assert.match(source,/track-detailed\.glb/);assert.match(source,/train-connector\.glb/);assert(fs.statSync('assets/models/kenney-train/track-detailed.glb').size>10000);assert(fs.statSync('assets/models/kenney-train/train-connector.glb').size>4000)});
test('an interactable conductor accompanies both platform and carriage',()=>{const f=fixture(),r=f.railway,source=fs.readFileSync('night-train.js','utf8');r.build();const conductors=f.interactables.filter(object=>object.userData.key==='conductor');assert(conductors.length>=8);assert.match(source,/function conductor\(/);assert.match(source,/Mind the sway\. The books travel better than some passengers\./);assert.match(source,/A station only exists for as long as someone wants to arrive\./);r.interact(conductors[0]);assert.match(f.notices.at(-1),/[“”]/)});
test('Lost in the Fog has a complete local public-domain edition and is loaded before the railway',()=>{const context={window:{ATHENAEUM_EXTRA_NOTES:{},ATHENAEUM_COVER_DESIGNS:{}}};vm.runInNewContext(fs.readFileSync('data/lost-in-the-fog.js','utf8'),context);const book=context.window.ATHENAEUM_FOG_BOOK,text=fs.readFileSync(book.textPath,'utf8'),local={window:{}};assert.equal(book.author,'J. D. Beresford');assert.equal(book.source,'Wikisource');assert.match(book.sourceUrl,/Nineteen_Impressions\/Lost_in_the_Fog/);assert(text.length>10000);assert.match(text,/LONDON was smothered in fog/);assert.match(text,/Surely it cannot be true/);vm.runInNewContext(fs.readFileSync('texts/local/pg900007.js','utf8'),local);assert.equal(local.window.ATHENAEUM_LOCAL_TEXTS[900007],text);const html=fs.readFileSync('index.html','utf8');assert(html.indexOf("startupScript('data/lost-in-the-fog.js')")<html.indexOf("startupScript('night-train.js')"));});
test('reduced motion freezes scenery and original railway ambience and old discoveries remain wired',()=>{const f=fixture(),r=f.railway;r.interact(r.entrance);r.interact(r.controls.board);r.interact(r.controls.depart);r.update(1,5,true,true,()=>{});const positions=r.groups.carriage.children.map(m=>m.position.z);r.update(2,5,true,true,()=>{});assert.deepEqual(r.groups.carriage.children.map(m=>m.position.z),positions);const game=fs.readFileSync('game.js','utf8');assert.match(game,/trainRumble:\{src:'assets\/audio\/train-rumble-distant.ogg'/);assert.match(game,/function beginTrainPass/);assert.match(game,/preRailReset=resetPosition/);assert.match(game,/nightRailway.cancel\(\)/);assert.match(game,/ui.pause.classList.contains\('hidden'\)/);assert.match(game,/createVerneDescent/);const html=fs.readFileSync('index.html','utf8');assert(html.indexOf("startupScript('night-train.js')")<html.indexOf("startupScript('game.js')"));});
test('actual reader-overlay wrapper advances the train, respects pause and mute, and stops looping audio on arrival',()=>{
  const f=fixture(),r=f.railway;r.interact(r.entrance);r.interact(r.controls.board);r.interact(conductorIn(f));assert(r.travelling);let now=0;const hidden={classList:{contains:()=>true}},reader={classList:{contains:()=>false}};
  const context={performance:{now:()=>now},worldIsCovered:()=>true,nightRailway:r,clock:{elapsedTime:0},document:{hidden:false},started:true,settingsOpen:false,chatOpen:false,supportOpen:false,ui:{reader,pause:hidden,journal:hidden},reducedMotion:false,sound:()=>{},soundLevel:.13,muted:false,samplePools:new Map(),clamp:(v,a,b)=>Math.max(a,Math.min(b,v)),Audio:class{constructor(src){this.src=src;this.paused=true}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}}};
  context.player=f.player;
  const game=fs.readFileSync('game.js','utf8'),start=game.indexOf('    const preRailCovered=worldIsCovered;'),end=game.indexOf("    document.addEventListener('visibilitychange'",start);vm.runInNewContext(game.slice(start,end),context);
  now+=50;assert(context.worldIsCovered());const audio=context.samplePools.get('nightRideRumble').pool[0];assert(!audio.paused);assert(audio.loop);assert.equal(audio.volume,.12);
  context.settingsOpen=true;now+=50;context.worldIsCovered();assert(audio.paused);assert(!r.arrived);context.settingsOpen=false;context.muted=true;now+=50;context.worldIsCovered();assert(audio.paused);context.muted=false;assert(r.travelling);
  for(let i=0;i<700;i++){now+=50;context.worldIsCovered()}assert(!r.travelling,'the 32-second run completes while reading');assert(audio.paused);assert.equal(audio.currentTime,0);
});
