const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const game=fs.readFileSync('game.js','utf8');
function functionSource(name){const start=game.indexOf(`function ${name}(`),open=game.indexOf('{',start);let depth=0;for(let i=open;i<game.length;i++){if(game[i]==='{')depth++;if(game[i]==='}'&&!--depth)return game.slice(start,i+1)}throw Error(name)}
// Registry has a destructured parameter, so take its declaration up to the next boot declaration.
const source=game.slice(game.indexOf('function createSingleCopyLibrary('),game.indexOf('    const singleCopyLibrary='));
function fixture(){const scene={visible:true},objects=[],context={};vm.runInNewContext(source+';this.create=createSingleCopyLibrary',context);let held=null;
 const registry=context.create({objects,scene,held:()=>held,priority:o=>o.userData.priority||0});
 function book(id,parent=scene,extra={}){const mesh={parent,visible:true,userData:{type:'book',book:{id,title:'Book '+id,author:'Writer',language:'en'},...extra}};objects.push(mesh);return mesh}
 return {scene,objects,registry,book,hold:o=>held=o};}
test('one title is visible and selectable across shelves, lazy rooms and progress displays',()=>{const f=fixture(),shelf=f.book(1),room={parent:f.scene,visible:true},themed=f.book(1,room,{priority:20}),display=f.book(1,f.scene,{priority:40,continueExtras:[{visible:true}]});f.registry.sync();assert.equal(shelf.visible,false);assert.equal(themed.visible,false);assert.equal(display.visible,true);assert.equal(f.registry.available().length,1);assert.equal(f.registry.find(shelf.userData.book),display);
 f.hold(themed);f.registry.sync();assert.equal(themed.visible,true);assert.equal(display.visible,false);assert.equal(display.userData.continueExtras[0].visible,false);
 themed.parent=f.scene;themed.userData.singleCopyMoved=true;f.hold(null);f.registry.sync();assert.equal(themed.visible,true);assert.equal(display.visible,false);assert.equal(f.registry.available().length,1);});
test('a book remains unique when a lazy room is unloaded and rebuilt',()=>{const f=fixture(),shelf=f.book(2),room={parent:f.scene,visible:true},themed=f.book(2,room,{priority:20});f.registry.sync();assert.equal(shelf.visible,false);room.parent=null;f.registry.sync();assert.equal(shelf.visible,true);assert.equal(themed.visible,false);f.objects.splice(f.objects.indexOf(themed),1);const rebuilt=f.book(2,{parent:f.scene,visible:true},{priority:20});f.registry.sync();assert.equal(rebuilt.visible,true);assert.equal(shelf.visible,false);});
test('room visibility scripts cannot expose duplicates or prematurely reveal a secret',()=>{const f=fixture(),shelf=f.book(3),secret=f.book(3,f.scene,{priority:100});secret.visible=false;f.registry.sync();assert.equal(secret.visible,false);assert.equal(shelf.visible,false);shelf.visible=true;assert.equal(shelf.visible,false);secret.visible=true;assert.equal(secret.visible,true);f.registry.sync();assert.equal(f.registry.available().length,1);});
test('duplicate editions share a title while translations and named volumes stay distinct',()=>{const f=fixture(),first=f.book(4),second=f.book(5),translation=f.book(6),volume=f.book(7);second.userData.book.title=first.userData.book.title;translation.userData.book.title=first.userData.book.title;translation.userData.book.language='fr';volume.userData.book.title=first.userData.book.title+' — Volume 2';f.registry.sync();assert.equal(first.visible,true);assert.equal(second.visible,false);assert.equal(translation.visible,true);assert.equal(volume.visible,true);assert.equal(f.registry.available().length,3);});
test('sitting down takes a real volume and makes no mesh or fallback copy',()=>{const f=fixture(),real=f.book(8),other=f.book(9);real.userData.book.progress=.1;other.userData.book.progress=.1;
 const vector={clone(){return this},set(){return this}},camera={position:vector,quaternion:vector,rotation:vector,updateMatrixWorld(){}};
 const context={seated:null,selected:null,carryingBook:false,themeZoneAt:()=>null,memoryZoneAt:()=>null,player:{pos:{},vel:vector},singleCopyLibrary:f.registry,tmpWorldPosition:{},keys:{},camera,$:()=>({}),openReader(){},selectBook(mesh){context.selected=mesh},showNotice(){context.notice=true},Math};vm.createContext(context);vm.runInContext(functionSource('sitWithBook')+';this.sit=sitWithBook',context);
 const seat={bookIds:[8],group:{updateWorldMatrix(){},localToWorld:v=>v},eye:vector,yaw:0};vector.copy=()=>vector;context.sit(seat);assert.equal(context.selected,real);assert.equal(f.objects.length,2);assert.equal(context.seated.seat,seat);
 context.selected=null;context.seated=null;context.sit({...seat,bookIds:[999]});assert.equal(context.selected,null);assert.equal(context.seated,null);assert.equal(context.notice,true);});
