const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function fixture(fail=false){
 class Vector{constructor(...v){this.v=v}clone(){return new Vector(...this.v)}copy(v){this.v=[...v.v];return this}fromArray(v){this.v=[...v];return this}add(){return this}}
 class Object3D{constructor(){this.children=[];this.parent=null;this.matrix=new Vector(1);this.matrixWorld=new Vector(1);this.position=new Vector();this.matrixAutoUpdate=true}add(...objects){for(const o of objects){o.removeFromParent();o.parent=this;this.children.push(o)}return this}removeFromParent(){if(this.parent){this.parent.children.splice(this.parent.children.indexOf(this),1);this.parent=null}}updateWorldMatrix(){}}
 class Camera extends Object3D{lookAt(){}updateMatrixWorld(){}}
 class Light extends Object3D{constructor(){super();this.target=new Object3D()}}
 const nodes={};function element(name){return nodes[name]||(nodes[name]={dataset:{},disabled:false,listeners:{},classList:{add(){},remove(){}},setAttribute(k,v){this[k]=v},focus(){document.activeElement=this},addEventListener(k,v){this.listeners[k]=v}})}
 const buttons=['moon','mars','out','in','close'].map(element);buttons[0].dataset.target='moon';buttons[1].dataset.target='mars';buttons[2].dataset.zoom='out';buttons[3].dataset.zoom='in';
 const canvas=element('canvas');let image;canvas.getContext=()=>({createImageData:(w,h)=>({data:new Uint8Array(w*h*4)}),putImageData:data=>image=data.data,clearRect(){}});
 const panel={...element('panel'),querySelector:s=>s==='canvas'?canvas:s==='.telescope-close'?buttons[4]:s==='[data-zoom="out"]'?buttons[2]:s==='[data-zoom="in"]'?buttons[3]:element(s),querySelectorAll:s=>s==='[data-target]'?buttons.slice(0,2):s==='[data-zoom]'?buttons.slice(2,4):buttons};
 const document={activeElement:element('previous'),body:{appendChild(){},classList:{add(){},remove(){}}},createElement:()=>panel},events={},window={addEventListener:(key,fn)=>events[key]=fn};
 const scene=new Object3D(),moonRoot=new Object3D(),marsRoot=new Object3D();scene.add(moonRoot,marsRoot);const initialTarget={},viewport=new Vector(5,6,7,8),scissor=new Vector(1,2,3,4);let renderTarget=initialTarget,currentViewport=viewport.clone(),currentScissor=scissor.clone(),scissorTest=true,disposed=0,renders=0,opened=0,closed=0,before=0;
 const renderer={autoClear:false,getRenderTarget:()=>renderTarget,setRenderTarget:t=>renderTarget=t,getViewport:v=>v.copy(currentViewport),setViewport:(...args)=>currentViewport=args[0] instanceof Vector?args[0].clone():new Vector(...args),getScissor:v=>v.copy(currentScissor),setScissor:v=>currentScissor=v.clone(),getScissorTest:()=>scissorTest,setScissorTest:v=>scissorTest=v,clear(){},render(){renders++;if(fail)throw Error('renderer failed')},readRenderTargetPixels(t,x,y,w,h,pixels){pixels.fill(10,0,w*4);pixels.fill(20,w*4)}};
 const THREE={Scene:Object3D,Color:class{},FogExp2:class{},Vector3:Vector,Vector4:Vector,HemisphereLight:Light,DirectionalLight:Light,PerspectiveCamera:Camera,SRGBColorSpace:'srgb',WebGLRenderTarget:class{constructor(){this.texture={}}dispose(){disposed++}}};
 const context={window,document,THREE,console:{warn(){}},Uint8Array};vm.runInNewContext(fs.readFileSync('telescope-view.js','utf8'),context);
 const viewer=window.createTelescopeViewer({THREE,renderer,scene,size:2,stars:()=>3,beforeRender:()=>before++,onOpen:()=>opened++,onClose:()=>closed++,destinations:{moon:{title:'Moon library',description:'Books on the Moon',view:()=>({root:moonRoot,eye:[0,3,5],look:[0,0,0]})},mars:{title:'Mars library',description:'Books on Mars',view:()=>({root:marsRoot,eye:[0,3,5],look:[0,0,0]})}}});
 return {viewer,renderer,scene,moonRoot,marsRoot,buttons,events,canvas,nodes,get image(){return image},get state(){return {renderTarget,currentViewport:currentViewport.v,currentScissor:currentScissor.v,scissorTest,disposed,renders,opened,closed,before}},initialTarget};
}
test('the telescope renders real roots, switches planets and restores world and renderer state',()=>{const f=fixture();f.viewer.open();assert.equal(f.viewer.isOpen,true);assert.equal(f.moonRoot.parent,f.scene);assert.equal(f.moonRoot.matrixAutoUpdate,true);assert.equal(f.state.renderTarget,f.initialTarget);assert.deepEqual(f.state.currentViewport,[5,6,7,8]);assert.deepEqual(f.state.currentScissor,[1,2,3,4]);assert.equal(f.state.scissorTest,true);assert.equal(f.renderer.autoClear,false);assert.equal(f.state.disposed,1);assert.deepEqual([...f.image.slice(0,8)],Array(8).fill(20),'readback is flipped upright');assert.match(f.canvas['aria-label'],/Moon library/);f.buttons[1].listeners.click();assert.match(f.canvas['aria-label'],/Mars library/);assert.equal(f.marsRoot.parent,f.scene);f.buttons[3].listeners.click();assert.equal(f.nodes.output.textContent,'1.25×');assert.equal(f.state.renders,3);f.viewer.close();assert.equal(f.viewer.isOpen,false);assert.equal(f.state.opened,1);assert.equal(f.state.closed,1);});
test('a failed render still restores roots, viewport, target and resources and can be closed',()=>{const f=fixture(true);f.viewer.open('mars');assert.equal(f.marsRoot.parent,f.scene);assert.equal(f.state.renderTarget,f.initialTarget);assert.equal(f.state.disposed,1);assert.equal(f.renderer.autoClear,false);assert.match(f.nodes['.telescope-caption'].textContent,/lens clouds over/);f.events.keydown({code:'Escape',preventDefault(){},stopImmediatePropagation(){}});assert.equal(f.viewer.isOpen,false);assert.equal(f.state.closed,1);});
test('Mars preview builds scenery without landing, tracking a visit or changing the hall atmosphere',()=>{const s=fs.readFileSync('mars.js','utf8'),body=s.match(/function preview\(\)\{([^\n]+)\}/)[1];assert.match(body,/if\(!root\)build\(\)/);assert.match(body,/object\.visible=false/);assert.doesNotMatch(body,/move\(|applyAtmosphere\(|setItem\(|analytics/);const game=fs.readFileSync('game.js','utf8');assert.match(game,/view:\(\)=>marsWorld\?\.preview\(\)/);assert.match(game,/view:\(\)=>highStaircase\.preview\(\)/);assert.match(game,/return telescopeViewer\?\.isOpen\|\|preTelescopeCovered\(\)/);});
